apiVersion: v1
kind: Pod
metadata:
  name: constantscore-test-pod
  labels:
    app: constantscore-test
spec:
  schedulerName: constantscore-scheduler
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
  restartPolicy: Always
