# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hyperai_pb2 as hyperai__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hyperai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HyperAIStub(object):
    """Central HyperAI service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScore = channel.unary_unary(
                '/hyperai.HyperAI/GetScore',
                request_serializer=hyperai__pb2.ScoreRequest.SerializeToString,
                response_deserializer=hyperai__pb2.ScoreReply.FromString,
                _registered_method=True)
        self.AgentConnect = channel.stream_stream(
                '/hyperai.HyperAI/AgentConnect',
                request_serializer=hyperai__pb2.AgentMessage.SerializeToString,
                response_deserializer=hyperai__pb2.ServerMessage.FromString,
                _registered_method=True)


class HyperAIServicer(object):
    """Central HyperAI service
    """

    def GetScore(self, request, context):
        """Scheduler -> Central server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentConnect(self, request_iterator, context):
        """Node Agent <-> Central server (bidirectional streaming control plane)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HyperAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScore,
                    request_deserializer=hyperai__pb2.ScoreRequest.FromString,
                    response_serializer=hyperai__pb2.ScoreReply.SerializeToString,
            ),
            'AgentConnect': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentConnect,
                    request_deserializer=hyperai__pb2.AgentMessage.FromString,
                    response_serializer=hyperai__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hyperai.HyperAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hyperai.HyperAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HyperAI(object):
    """Central HyperAI service
    """

    @staticmethod
    def GetScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hyperai.HyperAI/GetScore',
            hyperai__pb2.ScoreRequest.SerializeToString,
            hyperai__pb2.ScoreReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentConnect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hyperai.HyperAI/AgentConnect',
            hyperai__pb2.AgentMessage.SerializeToString,
            hyperai__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
