apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: scheduler-plugins
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: scheduler-plugins-scheduler
      plugins:
        multiPoint:
          enabled:
          - name: Coscheduling
          - name: CapacityScheduling
          - name: NodeResourcesAllocatable
          disabled:
          - name: PrioritySort
      pluginConfig:
      - name: Coscheduling
        args:
          permitWaitingTimeSeconds: 10
