// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: hyperai.proto

package hyperai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Original scheduler -> central server request
type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodJson       string                 `protobuf:"bytes,1,opt,name=pod_json,json=podJson,proto3" json:"pod_json,omitempty"`
	NodeJson      string                 `protobuf:"bytes,2,opt,name=node_json,json=nodeJson,proto3" json:"node_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_hyperai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetPodJson() string {
	if x != nil {
		return x.PodJson
	}
	return ""
}

func (x *ScoreRequest) GetNodeJson() string {
	if x != nil {
		return x.NodeJson
	}
	return ""
}

type ScoreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreReply) Reset() {
	*x = ScoreReply{}
	mi := &file_hyperai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReply) ProtoMessage() {}

func (x *ScoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReply.ProtoReflect.Descriptor instead.
func (*ScoreReply) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreReply) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// Messages sent from Agent to Server
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ScoreResponse
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_hyperai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetScoreResponse() *AgentScoreResponse {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_ScoreResponse); ok {
			return x.ScoreResponse
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ScoreResponse struct {
	ScoreResponse *AgentScoreResponse `protobuf:"bytes,3,opt,name=score_response,json=scoreResponse,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_ScoreResponse) isAgentMessage_Msg() {}

// Messages sent from Server to Agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_ScoreRequest
	//	*ServerMessage_Control
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_hyperai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetScoreRequest() *ServerScoreRequest {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ScoreRequest); ok {
			return x.ScoreRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetControl() *ServerControl {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_ScoreRequest struct {
	ScoreRequest *ServerScoreRequest `protobuf:"bytes,1,opt,name=score_request,json=scoreRequest,proto3,oneof"`
}

type ServerMessage_Control struct {
	Control *ServerControl `protobuf:"bytes,2,opt,name=control,proto3,oneof"` // reserved for future
}

func (*ServerMessage_ScoreRequest) isServerMessage_Msg() {}

func (*ServerMessage_Control) isServerMessage_Msg() {}

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_hyperai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHello) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentHello) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_hyperai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{5}
}

func (x *AgentHeartbeat) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ServerScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PodJson       string                 `protobuf:"bytes,2,opt,name=pod_json,json=podJson,proto3" json:"pod_json,omitempty"`
	NodeJson      string                 `protobuf:"bytes,3,opt,name=node_json,json=nodeJson,proto3" json:"node_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerScoreRequest) Reset() {
	*x = ServerScoreRequest{}
	mi := &file_hyperai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerScoreRequest) ProtoMessage() {}

func (x *ServerScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerScoreRequest.ProtoReflect.Descriptor instead.
func (*ServerScoreRequest) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{6}
}

func (x *ServerScoreRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerScoreRequest) GetPodJson() string {
	if x != nil {
		return x.PodJson
	}
	return ""
}

func (x *ServerScoreRequest) GetNodeJson() string {
	if x != nil {
		return x.NodeJson
	}
	return ""
}

type AgentScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentScoreResponse) Reset() {
	*x = AgentScoreResponse{}
	mi := &file_hyperai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentScoreResponse) ProtoMessage() {}

func (x *AgentScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentScoreResponse.ProtoReflect.Descriptor instead.
func (*AgentScoreResponse) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{7}
}

func (x *AgentScoreResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentScoreResponse) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AgentScoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerControl) Reset() {
	*x = ServerControl{}
	mi := &file_hyperai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerControl) ProtoMessage() {}

func (x *ServerControl) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerControl.ProtoReflect.Descriptor instead.
func (*ServerControl) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{8}
}

func (x *ServerControl) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerControl) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_hyperai_proto protoreflect.FileDescriptor

const file_hyperai_proto_rawDesc = "" +
	"\n" +
	"\rhyperai.proto\x12\ahyperai\"F\n" +
	"\fScoreRequest\x12\x19\n" +
	"\bpod_json\x18\x01 \x01(\tR\apodJson\x12\x1b\n" +
	"\tnode_json\x18\x02 \x01(\tR\bnodeJson\"\"\n" +
	"\n" +
	"ScoreReply\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\"\xc1\x01\n" +
	"\fAgentMessage\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.hyperai.AgentHelloH\x00R\x05hello\x127\n" +
	"\theartbeat\x18\x02 \x01(\v2\x17.hyperai.AgentHeartbeatH\x00R\theartbeat\x12D\n" +
	"\x0escore_response\x18\x03 \x01(\v2\x1b.hyperai.AgentScoreResponseH\x00R\rscoreResponseB\x05\n" +
	"\x03msg\"\x8e\x01\n" +
	"\rServerMessage\x12B\n" +
	"\rscore_request\x18\x01 \x01(\v2\x1b.hyperai.ServerScoreRequestH\x00R\fscoreRequest\x122\n" +
	"\acontrol\x18\x02 \x01(\v2\x16.hyperai.ServerControlH\x00R\acontrolB\x05\n" +
	"\x03msg\"\xfc\x01\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x127\n" +
	"\x06labels\x18\x04 \x03(\v2\x1f.hyperai.AgentHello.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eAgentHeartbeat\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\"k\n" +
	"\x12ServerScoreRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bpod_json\x18\x02 \x01(\tR\apodJson\x12\x1b\n" +
	"\tnode_json\x18\x03 \x01(\tR\bnodeJson\"}\n" +
	"\x12AgentScoreResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"=\n" +
	"\rServerControl\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\x88\x01\n" +
	"\aHyperAI\x128\n" +
	"\bGetScore\x12\x15.hyperai.ScoreRequest\x1a\x13.hyperai.ScoreReply\"\x00\x12C\n" +
	"\fAgentConnect\x12\x15.hyperai.AgentMessage\x1a\x16.hyperai.ServerMessage\"\x00(\x010\x01B+Z)sigs.k8s.io/scheduler-plugins/pkg/hyperaib\x06proto3"

var (
	file_hyperai_proto_rawDescOnce sync.Once
	file_hyperai_proto_rawDescData []byte
)

func file_hyperai_proto_rawDescGZIP() []byte {
	file_hyperai_proto_rawDescOnce.Do(func() {
		file_hyperai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperai_proto_rawDesc), len(file_hyperai_proto_rawDesc)))
	})
	return file_hyperai_proto_rawDescData
}

var file_hyperai_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hyperai_proto_goTypes = []any{
	(*ScoreRequest)(nil),       // 0: hyperai.ScoreRequest
	(*ScoreReply)(nil),         // 1: hyperai.ScoreReply
	(*AgentMessage)(nil),       // 2: hyperai.AgentMessage
	(*ServerMessage)(nil),      // 3: hyperai.ServerMessage
	(*AgentHello)(nil),         // 4: hyperai.AgentHello
	(*AgentHeartbeat)(nil),     // 5: hyperai.AgentHeartbeat
	(*ServerScoreRequest)(nil), // 6: hyperai.ServerScoreRequest
	(*AgentScoreResponse)(nil), // 7: hyperai.AgentScoreResponse
	(*ServerControl)(nil),      // 8: hyperai.ServerControl
	nil,                        // 9: hyperai.AgentHello.LabelsEntry
}
var file_hyperai_proto_depIdxs = []int32{
	4, // 0: hyperai.AgentMessage.hello:type_name -> hyperai.AgentHello
	5, // 1: hyperai.AgentMessage.heartbeat:type_name -> hyperai.AgentHeartbeat
	7, // 2: hyperai.AgentMessage.score_response:type_name -> hyperai.AgentScoreResponse
	6, // 3: hyperai.ServerMessage.score_request:type_name -> hyperai.ServerScoreRequest
	8, // 4: hyperai.ServerMessage.control:type_name -> hyperai.ServerControl
	9, // 5: hyperai.AgentHello.labels:type_name -> hyperai.AgentHello.LabelsEntry
	0, // 6: hyperai.HyperAI.GetScore:input_type -> hyperai.ScoreRequest
	2, // 7: hyperai.HyperAI.AgentConnect:input_type -> hyperai.AgentMessage
	1, // 8: hyperai.HyperAI.GetScore:output_type -> hyperai.ScoreReply
	3, // 9: hyperai.HyperAI.AgentConnect:output_type -> hyperai.ServerMessage
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hyperai_proto_init() }
func file_hyperai_proto_init() {
	if File_hyperai_proto != nil {
		return
	}
	file_hyperai_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ScoreResponse)(nil),
	}
	file_hyperai_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_ScoreRequest)(nil),
		(*ServerMessage_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperai_proto_rawDesc), len(file_hyperai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperai_proto_goTypes,
		DependencyIndexes: file_hyperai_proto_depIdxs,
		MessageInfos:      file_hyperai_proto_msgTypes,
	}.Build()
	File_hyperai_proto = out.File
	file_hyperai_proto_goTypes = nil
	file_hyperai_proto_depIdxs = nil
}
