apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperai-node-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperai-node-agent
  namespace: scheduler-plugins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperai-node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperai-node-agent
subjects:
  - kind: ServiceAccount
    name: hyperai-node-agent
    namespace: scheduler-plugins
