apiVersion: v1
kind: Service
metadata:
  name: hyperai-node-agent
  namespace: scheduler-plugins
  labels:
    app: hyperai-node-agent
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    app: hyperai-node-agent
