apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperai-scheduler-config
  namespace: scheduler-plugins
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: hyperai-scheduler
      plugins:
        filter:
          enabled:
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: NodeAffinity
        score:
          enabled:
          - name: HyperAI
        bind:
          enabled:
          - name: DefaultBinder
      pluginConfig:
      - name: HyperAI
        args:
          grpcAddress: "hyperai-grpc-service.scheduler-plugins.svc.cluster.local:50051"
          score: 42
