// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: hyperai.proto

package hyperai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_hyperai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ScoreRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ScoreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreReply) Reset() {
	*x = ScoreReply{}
	mi := &file_hyperai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreReply) ProtoMessage() {}

func (x *ScoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_hyperai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreReply.ProtoReflect.Descriptor instead.
func (*ScoreReply) Descriptor() ([]byte, []int) {
	return file_hyperai_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreReply) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_hyperai_proto protoreflect.FileDescriptor

const file_hyperai_proto_rawDesc = "" +
	"\n" +
	"\rhyperai.proto\x12\ahyperai\"F\n" +
	"\fScoreRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"\"\n" +
	"\n" +
	"ScoreReply\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score2C\n" +
	"\aHyperAI\x128\n" +
	"\bGetScore\x12\x15.hyperai.ScoreRequest\x1a\x13.hyperai.ScoreReply\"\x00B+Z)sigs.k8s.io/scheduler-plugins/pkg/hyperaib\x06proto3"

var (
	file_hyperai_proto_rawDescOnce sync.Once
	file_hyperai_proto_rawDescData []byte
)

func file_hyperai_proto_rawDescGZIP() []byte {
	file_hyperai_proto_rawDescOnce.Do(func() {
		file_hyperai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperai_proto_rawDesc), len(file_hyperai_proto_rawDesc)))
	})
	return file_hyperai_proto_rawDescData
}

var file_hyperai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hyperai_proto_goTypes = []any{
	(*ScoreRequest)(nil), // 0: hyperai.ScoreRequest
	(*ScoreReply)(nil),   // 1: hyperai.ScoreReply
}
var file_hyperai_proto_depIdxs = []int32{
	0, // 0: hyperai.HyperAI.GetScore:input_type -> hyperai.ScoreRequest
	1, // 1: hyperai.HyperAI.GetScore:output_type -> hyperai.ScoreReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hyperai_proto_init() }
func file_hyperai_proto_init() {
	if File_hyperai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperai_proto_rawDesc), len(file_hyperai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperai_proto_goTypes,
		DependencyIndexes: file_hyperai_proto_depIdxs,
		MessageInfos:      file_hyperai_proto_msgTypes,
	}.Build()
	File_hyperai_proto = out.File
	file_hyperai_proto_goTypes = nil
	file_hyperai_proto_depIdxs = nil
}
