// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: hyperai.proto

package hyperai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HyperAI_GetScore_FullMethodName = "/hyperai.HyperAI/GetScore"
)

// HyperAIClient is the client API for HyperAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperAIClient interface {
	GetScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreReply, error)
}

type hyperAIClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperAIClient(cc grpc.ClientConnInterface) HyperAIClient {
	return &hyperAIClient{cc}
}

func (c *hyperAIClient) GetScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreReply)
	err := c.cc.Invoke(ctx, HyperAI_GetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperAIServer is the server API for HyperAI service.
// All implementations must embed UnimplementedHyperAIServer
// for forward compatibility.
type HyperAIServer interface {
	GetScore(context.Context, *ScoreRequest) (*ScoreReply, error)
	mustEmbedUnimplementedHyperAIServer()
}

// UnimplementedHyperAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHyperAIServer struct{}

func (UnimplementedHyperAIServer) GetScore(context.Context, *ScoreRequest) (*ScoreReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedHyperAIServer) mustEmbedUnimplementedHyperAIServer() {}
func (UnimplementedHyperAIServer) testEmbeddedByValue()                 {}

// UnsafeHyperAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperAIServer will
// result in compilation errors.
type UnsafeHyperAIServer interface {
	mustEmbedUnimplementedHyperAIServer()
}

func RegisterHyperAIServer(s grpc.ServiceRegistrar, srv HyperAIServer) {
	// If the following call pancis, it indicates UnimplementedHyperAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HyperAI_ServiceDesc, srv)
}

func _HyperAI_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperAIServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperAI_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperAIServer).GetScore(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HyperAI_ServiceDesc is the grpc.ServiceDesc for HyperAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyperAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperai.HyperAI",
	HandlerType: (*HyperAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _HyperAI_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperai.proto",
}
